//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpPwIII
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public int IdTarea { get; set; }
        public int IdCarpeta { get; set; }
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> EstimadoHoras { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public short Prioridad { get; set; }
        public short Completada { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    }
}
